FROM node:18-slim

RUN apt-get update && apt-get -y install openssl jq
RUN yarn global add turbo

COPY --from=mwader/static-ffmpeg:5.1.2 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:5.1.2 /ffprobe /usr/local/bin/

WORKDIR /app

COPY package.json yarn.lock ./
COPY apps/ui/package.json ./apps/ui/
COPY apps/api/package.json ./apps/api/
COPY apps/api/prisma ./apps/api/prisma

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn workspace api prisma generate

COPY package.json /root/
RUN jq -r .version /root/package.json > /root/.version

CMD export VERSION=$(cat /root/.version) && yarn dev
