FROM node:18-slim

RUN apt-get update && apt-get -y install openssl procps
RUN npm install --global pnpm

WORKDIR /app

# Install ffmpeg
COPY --from=mwader/static-ffmpeg:5.1.2 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:5.1.2 /ffprobe /usr/local/bin/

# Copy only the files needed to install dependencies
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/prisma ./apps/api/
COPY apps/ui/package.json ./apps/ui/
COPY packages/common/package.json ./packages/common/
COPY packages/sdk/package.json ./packages/sdk/

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the files
COPY . .

# Generate prisma client
RUN pnpm api exec prisma generate

# Start the dev server
CMD pnpm dev
