create type "public"."setup_step" as enum ('CREATED_DATABASE', 'CREATED_USER', 'COMPLETED');

create table "public"."setup" (
    "id" bigint generated by default as identity not null,
    "step" setup_step not null
);


CREATE UNIQUE INDEX setup_pkey ON public.setup USING btree (id);

alter table "public"."setup" add constraint "setup_pkey" PRIMARY KEY using index "setup_pkey";


