FROM node:18-slim

RUN apt-get update && apt-get -y install openssl jq
RUN corepack enable pnpm

COPY --from=mwader/static-ffmpeg:5.1.2 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:5.1.2 /ffprobe /usr/local/bin/

WORKDIR /app

COPY apps/api/package.json apps/api/pnpm-lock.yaml ./
COPY apps/api/prisma prisma

RUN pnpm install --frozen-lockfile

COPY apps/api ./

RUN pnpm prisma generate

COPY package.json /root/
RUN jq -r .version /root/package.json > /root/.version

CMD export VERSION=$(cat /root/.version) && pnpm start:dev
