name: 'Deploy'

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      ENVIRONMENT_URL:
        required: true
        type: string
      KUBE_NAMESPACE:
        required: true
        type: string
      HELM_ARGS:
        required: true
        type: string

env:
  DOCKERFILE: Dockerfile
  HELM_CHART: tarrasqueapp
  IMAGE_NAME: tarrasqueapp
  KUBE_DEPLOYMENT: tarrasqueapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.ENVIRONMENT_URL }}

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE }}
          tags: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ENVIRONMENT }}
          build-args: |
            HOST=${{ inputs.ENVIRONMENT_URL }}
            NODE_ENV=production
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            SMTP_HOST=${{ secrets.SMTP_HOST }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SMTP_FROM=${{ secrets.SMTP_FROM }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.KUBE_CLUSTER }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          helm upgrade --install ${{ env.HELM_CHART }} ./helm/${{ env.HELM_CHART }} --namespace ${{ inputs.KUBE_NAMESPACE }} --create-namespace \
            --set image.repository=${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ inputs.ENVIRONMENT }} \
            --set env.HOST="${{ inputs.ENVIRONMENT_URL }}" \
            --set env.NODE_ENV="production" \
            --set env.SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            --set env.SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}" \
            --set env.SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            --set env.SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            --set env.SMTP_PORT="${{ secrets.SMTP_PORT }}" \
            --set env.SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}" \
            --set env.SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
            --set env.SMTP_FROM="${{ secrets.SMTP_FROM }}" \
            ${{ inputs.HELM_ARGS }}

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.KUBE_DEPLOYMENT }} --namespace ${{ inputs.KUBE_NAMESPACE }} --timeout 2m
